title: Joint_Variant_Call_hsa
about: Config file for references and modules

remote:
  ref_gnm: "/mnt/data/amedina/lupus/WGS/bam_files/hg38.fa"
  ref_vars: "/mnt/data/amedina/esalazarf/References/dbsnp157/dbSNP157.canon_chr.vcf.gz"
  modules: "gatk samtools mosdepth r/4.4.1"

local:
  ref_gnm: "$HOME/Data/REFx/hg38.p14/hg38.fa.gz"
  ref_vars: "$HOME/Data/REFx/dbSNP157/dbSNP157.canon_chr.vcf.gz"
  modules: ""
